FROM alpine AS qemu

#QEMU Download
ENV QEMU_URL https://github.com/balena-io/qemu/releases/download/v3.0.0%2Bresin/qemu-3.0.0+resin-aarch64.tar.gz
RUN apk add curl && curl -L ${QEMU_URL} | tar zxvf - -C . --strip-components 1

FROM arm32v7/python:rc-buster
COPY --from=qemu qemu-aarch64-static /usr/bin
RUN apt-get update && apt-get install -y postgresql-server-dev-all libpq-dev gcc
